#!/bin/sh
# Helper script to clean up the Docker containers and mounted build artifacts generated by containers.
# It would be nice to not use root user inside the container, but this is not yet in place.

sudo rm -rf .colcon/build .colcon/install .colcon/log

docker compose down --remove-orphans
