name: Test
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  build_and_test:
    name: ${{ matrix.package }} on ${{ matrix.distro }}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          push: false
          file: /home/runner/work/roscon24-workshop/roscon24-workshoproscon24-workshop/docker/Dockerfile
