name: Test
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  build_and_test:
    name: ${{ matrix.package }} on ${{ matrix.distro }}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and start docker
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yaml
          services: base
      # TODO: Add the following steps
      # - name: Run tests
      #   run: |
      #     docker compose exec base colcon build
      #     docker compose exec base colcon test
      #     docker compose exec base colcon test-result
